# Generated by Django 5.1.4 on 2025-01-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='pur_item_total_amount',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='pur_item_incoming',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='pur_item_purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='pur_item_received_items',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='pur_item_to_receive',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
