# Generated by Django 5.1.4 on 2025-01-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_remove_purchaseitem_pur_item_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='pur_item_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
