# Generated by Django 5.1.4 on 2025-01-08 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchaseitem_pur_item_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='po_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_order.purchaseorder'),
        ),
    ]
