# Generated by Django 5.1.4 on 2025-01-08 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_alter_purchaseitem_po_id'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='supplier.supplier'),
        ),
    ]
