# Generated by Django 5.1.4 on 2025-01-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_alter_purchaseorder_supp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='pur_item_to_receive',
        ),
    ]
