# Generated by Django 5.1.4 on 2025-01-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_contact_number'),
        ('purchase_order', '0006_remove_purchaseitem_pur_item_to_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login.user'),
        ),
    ]
