# Generated by Django 5.0.6 on 2025-01-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
    ]
