# Generated by Django 5.1.4 on 2025-01-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supp_id', models.AutoField(primary_key=True, serialize=False)),
                ('supp_name', models.CharField(max_length=100)),
                ('supp_contact_person', models.CharField(max_length=100, null=True)),
                ('supp_contact_number', models.CharField(max_length=100, null=True)),
                ('supp_address', models.CharField(max_length=255, null=True)),
                ('supp_address_info', models.CharField(max_length=255, null=True)),
                ('supp_emmail', models.EmailField(max_length=100, null=True)),
                ('supp_website', models.URLField(max_length=100, null=True)),
            ],
        ),
    ]
