# Generated by Django 5.1.4 on 2025-01-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supp_emmail',
            new_name='supp_email',
        ),
    ]
