# Generated by Django 5.1.4 on 2025-01-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_rename_supp_emmail_supplier_supp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supp_notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
