# Generated by Django 5.1.4 on 2025-01-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_supp_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supp_social_media',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
