# Generated by Django 5.1.4 on 2025-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_supp_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supp_address_info',
        ),
        migrations.AddField(
            model_name='supplier',
            name='sup_barangay',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sup_barangay_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sup_municipality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sup_municipality_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supp_provice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supp_provice_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supp_zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
