# Generated by Django 5.1.4 on 2025-01-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_remove_supplier_supp_address_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_barangay',
            new_name='supp_barangay',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_barangay_code',
            new_name='supp_barangay_code',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_municipality',
            new_name='supp_municipality',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='sup_municipality_code',
            new_name='supp_municipality_code',
        ),
    ]
