# Generated by Django 5.1.4 on 2025-01-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_rename_supp_provice_supplier_supp_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supp_barangay_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supp_municipality_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supp_province_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supp_zipcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
