# Generated by Django 5.1.4 on 2025-01-13 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_alter_supplier_supp_barangay_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 23, 15, 1, 394574, tzinfo=datetime.timezone.utc)),
        ),
    ]
