# Generated by Django 5.0.6 on 2024-12-28 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('sold_by', models.CharField(choices=[('each', 'Each'), ('volume_weight', 'Volume/Weight')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.PositiveIntegerField()),
                ('optimal_stock', models.PositiveIntegerField()),
                ('reorder_level', models.PositiveIntegerField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_category.category')),
            ],
        ),
    ]
