# Generated by Django 5.0.6 on 2024-12-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_composite',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompositeItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_composites', to='item_list.item')),
                ('composite_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='item_list.item')),
            ],
        ),
    ]
