# Generated by Django 5.0.6 on 2024-12-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0002_item_is_composite_compositeitemcomponent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompositeItemComponent',
        ),
    ]
