# Generated by Django 5.0.6 on 2024-12-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0003_delete_compositeitemcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('component_item', models.ForeignKey(limit_choices_to={'is_composite': False}, on_delete=django.db.models.deletion.CASCADE, related_name='part_of_composites', to='item_list.item')),
                ('composite_item', models.ForeignKey(limit_choices_to={'is_composite': True}, on_delete=django.db.models.deletion.CASCADE, related_name='composite_components', to='item_list.item')),
            ],
        ),
    ]
