# Generated by Django 5.0.6 on 2024-12-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0010_compositeitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompositeItem',
        ),
    ]
