# Generated by Django 5.0.6 on 2024-12-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0011_delete_compositeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_list.item')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_items', to='item_list.item')),
            ],
        ),
    ]
