# Generated by Django 5.0.6 on 2024-12-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0012_compositeitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompositeItem',
        ),
    ]
