# Generated by Django 5.0.6 on 2024-12-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0015_compositeitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold_by',
            field=models.CharField(blank=True, choices=[('each', 'Each'), ('volume_weight', 'Volume/Weight')], max_length=50, null=True),
        ),
    ]
