# Generated by Django 5.0.6 on 2025-01-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0020_alter_item_purchase_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='optimal_stock',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
