# Generated by Django 5.0.6 on 2025-01-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0028_item_cost_per_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost_per_m',
        ),
    ]
