# Generated by Django 5.0.6 on 2025-01-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0029_remove_item_cost_per_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_per_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
