# Generated by Django 5.0.6 on 2025-01-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0030_item_cost_per_m'),
        ('supplier', '0004_supplier_supp_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier'),
        ),
    ]
