# Generated by Django 5.1.4 on 2025-01-14 05:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_list', '0031_item_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('notes', models.TextField(null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('denial_reason', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_list.item')),
                ('item_req', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', to='item_request.itemrequest')),
            ],
        ),
    ]
