# Generated by Django 5.1.4 on 2025-01-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteditem',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
